model:
  model_name: "../train/output/vlm_finetuned"
  torch_dtype_str: "bfloat16"
  trust_remote_code: True
  model_max_length: 9216
  attn_implementation: flash_attention_2
  chat_template: "qwen2-vl-instruct"

inference_engine: NATIVE

# List of tasks to evaluate (only a single task in this case).
tasks:
  - evaluation_backend: custom
    task_name: Counting_tools_evaluation

output_dir: "output/evaluation"

generation:
  batch_size: 1
  max_new_tokens: 2048
  use_cache: True
  use_sampling: False

run_name: "Debug"
enable_wandb: True