model:
  model_name: "Qwen/Qwen2.5-VL-7B-Instruct" # "/workspace/models/tool_thinker-0.1" "Qwen/Qwen2.5-VL-7B-Instruct"
  torch_dtype_str: "bfloat16"
  trust_remote_code: True
  model_max_length: 65536
  attn_implementation: flash_attention_2
  chat_template: "qwen2-vl-instruct"

inference_engine: VLLM

# List of tasks to evaluate (only a single task in this case).
tasks:
  - evaluation_backend: custom
    task_name: Counting_tools_evaluation

output_dir: "output/evaluation"

generation:
  batch_size: 1
  max_new_tokens: 2048
  use_cache: True
  use_sampling: False
  temperature: 0.0

run_name: "Debug"
enable_wandb: True