data:
  train_files: BLINK-Benchmark/BLINK
  val_files: BLINK-Benchmark/BLINK
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 6656
  max_response_length: 1536 #2048
  rollout_batch_size: 64 # 512
  val_batch_size: 1024 # 1024
  format_prompt: ./examples/format_prompt/tools_thinker_pure_w_think_wo_system.jinja
  override_chat_template: null
  shuffle: true
  seed: 42
  max_pixels: 4194304
  min_pixels: 262144
  filter_overlong_prompts: false
  subtasks: # ["Counting"]  # ["Counting","Art_Style"] # subtasks list or null
  dataset_prefix:  # Dataset root path # BLINK:/home/stud/wxie # SAT:/nfs/data8/liao/wxie/SAT/
  tools_config: ./examples/tools_config/tools_configuration_file.yaml
  double_modes: false # True
  dataset_json: "/workspace/ywen_ws/datasets/spatial457_wo_L5(8400)_random.json" # spatial457_wo_L5(8670).json"

algorithm:
  adv_estimator: grpo
  disable_kl: true # true
  use_kl_loss: false # false
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2

worker:
  actor:
    global_batch_size: 32 # 128 for update glable_batch size * n // num_gpu
    micro_batch_size_per_device_for_update: 4 # 4
    micro_batch_size_per_device_for_experience: 16 # 16
    max_grad_norm: 1.0
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw_bf16  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
      torch_dtype: bf16 # add flash-attn2 (Ampere GPU) 
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 8 # 5
    temperature: 1.0
    top_p: 0.99
    gpu_memory_utilization: 0.6 # 0.6
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    max_num_batched_tokens: 16384
    limit_images: 3
    val_override_config:
      temperature: 0.5
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
      torch_dtype: bf16 # add flash-attn2 (Ampere GPU) 
    offload:
      offload_params: false

  reward:
    reward_type: batch
    reward_function: ./examples/reward_function/tool_language_reward_concurrent_dd _w_code_length.py:compute_score # ./examples/reward_function/tool_reward.py:compute_score
    reward_function_kwargs:
      think_length_weight: 0.25
      code_think_length_weight: 0.25
      format_weight: 0.1
      usage_weight: 0.2
      execution_weight: 0.2
      accuracy_weight: 0.5
      nl_accuracy_weight: 0.5 # automatically set format_weight = (1 - nl_accuracy_weight - think_length_weight)
      root_dir: /workspace/models/exp_pure_code_spatial457_w_code_len_logs
      diversity_scale: false
    num_gpus: 0
    num_cpus: 1

trainer:
  total_epochs: 1 # 15
  # max_steps: 50
  project_name: Debug # easyr1
  experiment_name: qwen2_5_debug
  logger: ["console", "wandb"]
  nnodes: 1
  n_gpus_per_node: 8
  val_freq: 100  # -1 to disable default:5
  val_before_train: false # true
  val_only: false
  val_generations_to_log: 3
  save_freq: 10  # -1 to disable
  save_limit: -1  # -1 to disable
  save_checkpoint_path: /workspace/models/ckpt/exp_pure_code_spatial457_w_code_len/
  load_checkpoint_path: null