prompt_template: |
  Generate Python program to solve the following question based on given tools module step by step.
  You now have the ability to write selectively executable Python code to help you answer question.
  You need to wrap code you write at each step with <code></code> tags when using a tool. 
  The code within these tags will be sent to the interpreter for execution. 
  The returned result (wrapped in <inter></inter> tags) will serve as the intermediate result for your reasoning. 
  You should use these intermediate results as input for your next tool usage, reasoning and writing code step by step until you believe you have reached the correct answer.

  Feel free to select single tool or combine the tools that are most suitable for solving the task.
  Available Tools List:  {available_tools}
  Tools Metadata(Dict):  {toolbox_metadata}

  Important instructions:
  1.must not call tools if they are not useful for solving the problem.
  2.The returned result in <inter></inter> can be either the direct result of the execution, having the same content type as specified in the metadata, the path to a `.npy` file where the result is stored, or error report.
  3.assign your final answer for question to a python variable named `final_result` within the Python code.
  4.Write your thought process step by step on how to solve the problem, and then write the code.
  5.use the provided image path: `{image_paths}`.

  **Think Format**:
  Each thought process is wrapped with
  <think>
  thought part
  </think>

  **Code Format**:
  Each code snippet is wrapped with
  <code>
  code snippet
  </code>

  **Answer Format**:
  The last part of your response should be:
  <answer>\boxed{{'The final answer goes here.'}}</answer>

  Question: 
  {question}

