prompt_template: |
  You are a helpful AI assistant.
  {question}.
  Note that for visual reasoning questions about the existence of something, your answers should be true/false. 
  Make sure to write your final answer inside `\boxed{{}}` brackets.