model:
  model_name: "Qwen/Qwen2.5-VL-7B-Instruct"
  torch_dtype_str: "bfloat16"
  model_max_length: 65536
  trust_remote_code: True
  attn_implementation: "flash_attention_2" # sdqa # You can also use `flash_attention_2` if you install it
  chat_template: "qwen2-vl-instruct" # 2.5 uses the same template as 2.0
  freeze_layers: # Freeze specific layers to only train the language model, and not the vision encoder
    - "visual"

data:
  train:
    collator_name: "vision_language_with_padding"
    use_torchdata: True
    datasets:
      - dataset_name: "vl_sft" # vl_sft_jsonl / vl_sft
        dataset_path: /workspace/ywen_ws/mix_datasets/train.jsonl # "/workspace/ywen_ws/mix_datasets/last_round_train.jsonl"
        shuffle: True
        seed: 42
        transform_num_workers: "auto"
        dataset_kwargs:
          processor_name: "Qwen/Qwen2.5-VL-7B-Instruct"
          # limit: 4096 # Uncomment to limit dataset size!
          return_tensors: True

training:
  output_dir: "/workspace/models/tool_thinker-0.1"
  trainer_type: "TRL_SFT"
  enable_gradient_checkpointing: True
  per_device_train_batch_size: 1 # Must be 1: the model generates variable-sized image features
  gradient_accumulation_steps: 8
  # max_steps: 20 # Uncomment if you want to limit the number of training steps.
  num_train_epochs: 2
  use_peft: False # disable lora

  gradient_checkpointing_kwargs:
    # Reentrant docs: https://pytorch.org/docs/stable/checkpoint.html#torch.utils.checkpoint.checkpoint
    use_reentrant: False
  ddp_find_unused_parameters: False
  empty_device_cache_steps: 1
  compile: False

  optimizer: "adamw_torch_fused"
  learning_rate: 2e-5
  warmup_ratio: 0.03 # 0.2 # 0.03
  weight_decay: 0.01
  lr_scheduler_type: "cosine"

  logging_steps: 1
  save_steps: 0
  save_final_model: true
  dataloader_main_process_only: False
  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 8
  include_performance_metrics: True
  log_model_summary: False
  enable_wandb: True

peft:
  q_lora: False
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  lora_target_modules:
    - "q_proj"
    - "v_proj"
    - "o_proj"
    - "k_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  lora_init_weights: DEFAULT
